// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udoxhiifzfxfmegggipl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkb3hoaWlmemZ4Zm1lZ2dnaXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjYzNDMsImV4cCI6MjA2NDM0MjM0M30.2bv0QfOWQSGphl9yJC3aZpw4HjrVo7OD8vKuYrh6xdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);